- name: return secrets as a dict (default)
  ansible.builtin.set_fact:
    component_secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{component_name}} token={{ vault_token }} url=http://vault-internal.kommanuthala.store:8200') }}"

- name: Copy Systemd service
  ansible.builtin.template:
    src: component.service
    dest: "/etc/systemd/system/catalogue.service"

- name: Start service
  ansible.builtin.systemd_service:
    name: "{{ component_name }}"
    state: restarted 
    enabled: yes
    daemon-reload: yes